name: Release to prod legacy
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: Cere-IO/reusable-workflows/.github/workflows/build-and-upload-static.yaml@master
    with:
      runs-on: '["self-hosted", "cere-io-large-workers"]'
      build_container: 'node:18-buster'
      deploy_container: 'ubuntu:20.04'
      install_packages_command: 'cp .env.prod-legacy .env; npm ci'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'build'
    secrets:
      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.PRD_CORE_AWS_ACCESS_KEY_ID }}
      NETWORK_AWS_SECRET_ACCESS_KEY: ${{ secrets.PRD_CORE_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_PRD_LEGACY }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID_PRD_LEGACY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
