name: Run simulation

on:
  workflow_dispatch:
    inputs:
      auth-network:
        description: Web3Auth network
        required: true
        type: choice
        default: testnet
        options:
          - testnet
          - mainnet
          - cyan

      iterations:
        description: 'Number of iterations'
        required: true
        type: number
        default: 10

      instances:
        description: 'Number of browser instances'
        required: true
        type: number
        default: 1

jobs:
  tests:
    name: Simulation
    uses: ./.github/workflows/wdio-tests.yaml
    with:
      max-instances: ${{ inputs.instances }}
      keep-report-history: 20
      report-dir: simulations
      install_packages_command: cp .env.simulation-${{ inputs.auth-network }} .env; npm ci
      build_command: npm run build
      test_command: |
        npm run test:ci -- \
          --suite=simulation \
          --maxInstances=${{ inputs.instances }} \
          --multi-run=${{ inputs.iterations }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
