name: Run tests

on: [pull_request, workflow_dispatch]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_READ}}
        run: cp .env.test .env; npm ci

      - name: Build applications
        run: npm run build

      - name: Run tests
        run: npm run test:ci
